# Read the Docs configuration file
# See https://docs.readthedocs.com/platform/en/stable/config-file/index.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: conf.py
  fail_on_warning: false

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - method: poetry
      path: .
      groups:
        - docs

# Formats to build (PDF and ePub disabled for faster builds)
formats: []
