#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys

sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = 'ActingWeb'
copyright = '2020, Greger Teigre Wedel'
author = 'Greger Teigre Wedel'

# The short X.Y version
version = ''
# The full version, including alpha/beta/rc tags
release = '2.6.1'


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.todo',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
    'sphinx.ext.autosectionlabel',
    'sphinx.ext.intersphinx',
    'sphinx_copybutton',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = {'.rst': 'restructuredtext'}

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = [
    '_build',
    'Thumbs.db',
    '.DS_Store',
    'actingweb.egg-info',
    'dist',
    '.venv',
    '.venv/**',
    'venv',
    'venv/**',
]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = None


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# Note: Empty list since we have no custom static files
html_static_path: list[str] = []

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'ActingWebdoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'ActingWeb.tex', 'ActingWeb Documentation',
     'Greger Teigre Wedel', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'actingweb', 'ActingWeb Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'ActingWeb', 'ActingWeb Documentation',
     author, 'ActingWeb', 'One line description of project.',
     'Miscellaneous'),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']


# -- Extension configuration -------------------------------------------------

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# Intersphinx mappings for richer cross-references
intersphinx_mapping = {
    'python': ('https://docs.python.org/3/', None),
    'flask': ('https://flask.palletsprojects.com/en/latest/', None),
    'boto3': ('https://boto3.amazonaws.com/v1/documentation/api/latest/', None),
    'pynamodb': ('https://pynamodb.readthedocs.io/en/latest/', None),
    'pydantic': ('https://docs.pydantic.dev/latest/', None),
}

# Suppress warnings for type references that can't be resolved
# These are primarily from autodoc processing docstrings with type hints
# to external packages that don't provide intersphinx inventories
nitpick_ignore = [
    # Python types module
    ('py:class', 'ModuleType'),
    # Internal actingweb classes that aren't exposed in docs
    ('py:class', 'HookRegistry'),
    ('py:class', 'AuthenticatedActorView'),
    ('py:class', 'config_class.Config'),
    ('py:class', 'actingweb.subscription_config.SubscriptionProcessingConfig'),
    ('py:class', 'actingweb.interface.property_store.PropertyStore'),
    ('py:class', 'actingweb.interface.subscription_manager.SubscriptionManager'),
    ('py:class', 'actingweb.interface.trust_manager.TrustManager'),
    ('py:class', 'actingweb.interface.hooks.HookMetadata'),
    ('py:class', 'actingweb.interface.hooks.HookRegistry'),
    ('py:class', 'actingweb.interface.integrations.base_integration.BaseActingWebIntegration'),
    # Pydantic classes (intersphinx doesn't always work well)
    ('py:class', 'pydantic.main.BaseModel'),
    ('py:class', 'ConfigDict'),
    # FastAPI/Starlette classes (intersphinx doesn't always work well)
    ('py:class', 'fastapi.applications.FastAPI'),
    ('py:class', 'starlette.requests.Request'),
    ('py:class', 'starlette.responses.Response'),
    ('py:class', 'starlette.responses.RedirectResponse'),
]

# Only label top-level sections to avoid duplicate labels
autosectionlabel_maxdepth = 1

# Autosectionlabel options
autosectionlabel_prefix_document = True
