"""
ListProperty implementation for ActingWeb distributed list storage.

This module provides a list interface that stores list items as individual
properties in DynamoDB, bypassing the 400KB limit while maintaining API compatibility.
"""

import json
import logging
import re
from collections.abc import Iterator
from datetime import datetime
from typing import Any

import fractional_indexing as fi

from actingweb.db import get_property, get_property_list

logger = logging.getLogger(__name__)

# v2 storage format (fractional rank keys) -- see "Phase 4" of
# thoughts/plans/2026-08-08-property-list-index-integrity.md.
#
# Item rows are named "list:{name}-#{rank}" where {rank} is a
# fractional-indexing key (base62: '0'-'9','A'-'Z','a'-'z', ASCII 0x30-0x7A).
# The '#' marker (0x23) is what isolates a list's v2 rows from everything
# else sharing the "list:{name}-" prefix:
#   - v1 item rows "list:{name}-N" start with a digit (0x30-0x39) > '$'
#   - the meta row "list:{name}-meta" starts with 'm' (0x6D) > '$'
#   - a SIBLING list "list:{name}-x-#..." starts with 'x' (or any non-'#'
#     char) > '#', so it's excluded by the '<= upper' bound
# This is also why new list names may never contain '#': a list literally
# named "{name}-#suffix" would put its own v2 rows inside {name}'s range.
#
# That name ban only binds NEW lists, though. A list created before Phase 4
# and legitimately named e.g. "foo-#bar" keeps working as v1 indefinitely
# (migration refuses '#' names), and its rows -- "list:foo-#bar-0",
# "list:foo-#bar-meta" -- DO fall inside v2 list "foo"'s byte range. The
# range bounds alone therefore do not isolate a v2 list; every consumer of
# a range read must additionally check that the part after the '#' marker
# is a well-formed rank key via _v2_is_rank(). Rank keys are pure base62,
# and every v1 row name ends in "-{digits}" or "-meta", so the '-' in a
# legacy sibling's suffix is what gives it away.
_V2_RANK_MARKER = "#"
_V2_RANK_MAX_LEN = 180
_V2_MAX_RANK_RETRIES = 8
_V2_LAZY_MIGRATION_MAX_LENGTH = 50
_V2_RANK_ALPHABET = frozenset(fi.BASE_62_DIGITS)


def _v2_is_rank(candidate: str) -> bool:
    """True if ``candidate`` is a well-formed v2 rank key.

    Rank keys generated by ``fractional_indexing`` are non-empty strings
    drawn entirely from its base62 alphabet. Anything else sharing a v2
    list's byte range belongs to a legacy ``#``-named sibling list (whose
    row names always carry a ``-{index}``/``-meta`` suffix, and ``-`` is
    not in the alphabet) and must be filtered out -- see the module
    comment above.
    """
    return bool(candidate) and not (set(candidate) - _V2_RANK_ALPHABET)


class ListCorruptionError(IndexError):
    """A list item within the recorded length is missing from storage.

    Distinct from a genuine out-of-range ``IndexError``: this means the row
    at ``index`` should exist (``0 <= index < length``) but does not -- the
    signature an interrupted delete/insert shift leaves (see
    thoughts/research/2026-08-07-property-list-index-integrity.md). Being an
    ``IndexError`` subclass, existing ``except IndexError`` call sites keep
    working; new code can catch this specifically to offer a repair path.
    The message carries only the list name and index, never item values.
    """

    def __init__(self, list_name: str, index: int) -> None:
        self.list_name = list_name
        self.index = index
        super().__init__(
            f"List '{list_name}' item at index {index} is missing from "
            f"storage (recorded length claims it should exist); run "
            f"compact() to repair"
        )


class ListPropertyIterator:
    """
    Lazy-loading iterator for ListProperty.

    Loads list items on-demand to minimize database queries and memory usage.
    """

    def __init__(self, list_prop: "ListProperty") -> None:
        self.list_prop = list_prop
        self.current_index = 0

    def __iter__(self) -> "ListPropertyIterator":
        return self

    def __next__(self) -> Any:
        if self.current_index >= len(self.list_prop):
            raise StopIteration

        item = self.list_prop[self.current_index]
        self.current_index += 1
        return item


class ListProperty:
    """
    Distributed list storage implementation for ActingWeb properties.

    Metadata lives at ``list:{name}-meta``; its ``format`` field selects
    the item-row storage layout (dispatched throughout this class via
    ``_is_v2()``):

    - format 1 (absent/1, "v1"): items at ``list:{name}-{index}``, dense
      integers 0..length-1, authoritative ``length`` in metadata. Every
      list created before Phase 4 shipped.
    - format 2 ("v2"): items at ``list:{name}-#{rank}``, fractional
      ("rank") keys that sort into item order -- length is always counted
      from the rank-key range, never stored. Every NEW list as of Phase 4.
    """

    def __init__(self, actor_id: str, name: str, config: Any) -> None:
        self.actor_id = actor_id
        self.name = name
        self.config = config
        self._meta_cache: dict[str, Any] | None = None
        self._db = get_property(self.config) if self.config else None
        # v2 only: sorted list of rank-key suffixes (without the
        # "list:{name}-#" prefix), lazily loaded. None means "not loaded
        # yet"; [] is a valid loaded-and-empty state.
        self._v2_rank_cache: list[str] | None = None

    def _get_meta_property_name(self) -> str:
        """Get the metadata property name."""
        return f"list:{self.name}-meta"

    def _get_item_property_name(self, index: int) -> str:
        """Get the property name for a list item at given index (v1 only)."""
        return f"list:{self.name}-{index}"

    def _format(self) -> int:
        """The storage format this list uses: 1 (dense integers, the
        original format) or 2 (fractional rank keys). Absent/unparsable
        `format` in metadata means 1 -- every list created before Phase 4
        shipped."""
        meta = self._load_metadata()
        try:
            return int(meta.get("format", 1) or 1)
        except (TypeError, ValueError):
            return 1

    def _is_v2(self) -> bool:
        return self._format() == 2

    def _decode_item(self, item_str: str) -> Any:
        try:
            return json.loads(item_str)
        except (json.JSONDecodeError, TypeError) as e:
            logger.error(f"Failed to parse list item for '{self.name}': {e}")
            return item_str

    def _encode_item(self, item: Any) -> str:
        try:
            return json.dumps(item)
        except (TypeError, ValueError):
            return str(item)

    # -- v2 (fractional rank key) helpers -----------------------------

    def _v2_item_prefix(self) -> str:
        return f"list:{self.name}-{_V2_RANK_MARKER}"

    def _v2_item_name(self, rank: str) -> str:
        return f"{self._v2_item_prefix()}{rank}"

    def _v2_bounds(self) -> tuple[str, str]:
        """Inclusive [lower, upper] bounds for get_range() that cover
        exactly this list's v2 item rows -- see the module docstring."""
        return (self._v2_item_prefix(), f"list:{self.name}-$")

    def _v2_ensure_rank_cache(self, force: bool = False) -> list[str]:
        """Return the sorted rank-key cache, loading it (one keys-only
        range query) if absent or `force`d. The returned list is the SAME
        object held in `self._v2_rank_cache` -- callers that insert/delete
        a single entry may mutate it in place instead of forcing a reload."""
        if self._v2_rank_cache is not None and not force:
            return self._v2_rank_cache
        lower, upper = self._v2_bounds()
        db = get_property(self.config)
        rows = db.get_range(
            actor_id=self.actor_id, lower=lower, upper=upper, keys_only=True
        )
        prefix_len = len(self._v2_item_prefix())
        self._v2_rank_cache = sorted(
            rank for name in rows if _v2_is_rank(rank := name[prefix_len:])
        )
        return self._v2_rank_cache

    def _v2_load_full(self) -> list[tuple[str, str]]:
        """One full range query -> sorted (rank, raw_value) pairs. Also
        refreshes the rank-key cache as a side effect (the invariant that
        to_list()/__iter__/slice() cost exactly one query, and warm the
        cache for any __getitem__ calls that follow)."""
        lower, upper = self._v2_bounds()
        db = get_property(self.config)
        rows = db.get_range(actor_id=self.actor_id, lower=lower, upper=upper)
        prefix_len = len(self._v2_item_prefix())
        pairs = sorted(
            (rank, value)
            for name, value in rows.items()
            if _v2_is_rank(rank := name[prefix_len:])
        )
        self._v2_rank_cache = [rank for rank, _ in pairs]
        return pairs

    def _v2_to_list(self) -> list[Any]:
        return [self._decode_item(value) for _, value in self._v2_load_full()]

    def _create_default_metadata_v2(self) -> dict[str, Any]:
        """Default metadata for a brand-new (v2) list. No `length` key --
        v2 has no authoritative stored length, it's always counted from the
        rank-key range."""
        now = datetime.now().isoformat()
        return {
            "format": 2,
            "created_at": now,
            "updated_at": now,
            "item_type": "json",
            "chunk_size": 1,
            "version": "1.0",
            "description": "",
            "explanation": "",
        }

    def _load_metadata(self) -> dict[str, Any]:
        """Load metadata from database, with caching."""
        if self._meta_cache is not None:
            return self._meta_cache

        if not self._db:
            return self._create_default_metadata()

        # Use fresh DB instance to avoid handle conflicts
        meta_db = get_property(self.config)
        meta_str = meta_db.get(
            actor_id=self.actor_id, name=self._get_meta_property_name()
        )

        if meta_str is None:
            # No metadata exists - this is a new list, created directly in
            # the v2 (fractional rank key) format.
            if _V2_RANK_MARKER in self.name:
                raise ValueError(
                    f"List name '{self.name}' cannot contain "
                    f"'{_V2_RANK_MARKER}' -- reserved for internal storage "
                    f"keys (a list named '...{_V2_RANK_MARKER}...' would "
                    f"put its item rows inside another list's storage "
                    f"range)"
                )

            # Check for property collision - error if property exists
            prop_db = get_property(self.config)
            existing_prop = prop_db.get(actor_id=self.actor_id, name=self.name)
            if existing_prop is not None:
                raise ValueError(
                    f"Cannot create list '{self.name}': a property with this name already exists. "
                    f"Delete the property first or use a different name."
                )

            # No metadata exists, create default
            # Don't save yet - let the caller save via set_description/set_explanation
            meta = self._create_default_metadata_v2()
            self._meta_cache = (
                meta  # Cache it for subsequent calls within this instance
            )
            return meta

        try:
            parsed_meta = json.loads(meta_str)
        except (json.JSONDecodeError, TypeError) as e:
            # Do NOT self-heal by writing a fresh default: that orphans
            # every existing item row (length: 0 with no way back to them).
            # An unparsable metadata row means real corruption -- raise so
            # the caller can run verify()/compact() (or the operator can
            # inspect the row directly) instead of silently losing data.
            raise ValueError(f"Unparsable metadata for list '{self.name}': {e}") from e
        if not isinstance(parsed_meta, dict):
            raise ValueError(
                f"Metadata for list '{self.name}' is not a JSON object "
                f"(got {type(parsed_meta).__name__})"
            )
        self._meta_cache = parsed_meta
        return self._meta_cache

    def _create_default_metadata(self) -> dict[str, Any]:
        """Create default metadata structure."""
        now = datetime.now().isoformat()
        return {
            "length": 0,
            "created_at": now,
            "updated_at": now,
            "item_type": "json",
            "chunk_size": 1,
            "version": "1.0",
            "description": "",
            "explanation": "",
        }

    def _save_metadata(self, meta: dict[str, Any]) -> None:
        """Save metadata to database and update cache."""
        meta["updated_at"] = datetime.now().isoformat()

        if self._db:
            meta_property_name = self._get_meta_property_name()
            meta_json = json.dumps(meta)
            # Use fresh DB instance to avoid handle conflicts
            meta_db = get_property(self.config)
            if not meta_db.set(
                actor_id=self.actor_id, name=meta_property_name, value=meta_json
            ):
                raise RuntimeError(f"list metadata write failed for '{self.name}'")

        self._meta_cache = meta

    def _invalidate_cache(self) -> None:
        """Invalidate the metadata cache."""
        self._meta_cache = None

    def prime_from_rows(self, rows: dict[str, Any]) -> None:
        """Hydrate the metadata cache (and, for v2, the rank-key cache)
        from a pre-fetched name->value mapping.

        `rows` is the result of a bulk fetch_all_including_lists() read.
        Priming avoids re-reading the `list:<name>-meta` row that the bulk
        read already returned, and for v2 lists also avoids a separate
        range query for length/positional lookups. Ignores missing or
        unparsable metadata (the normal lazy path then applies).
        """
        meta_str = rows.get(self._get_meta_property_name())
        if meta_str is None:
            return
        try:
            parsed = json.loads(meta_str)
        except (json.JSONDecodeError, TypeError):
            return
        if not isinstance(parsed, dict):
            return
        self._meta_cache = parsed
        if int(parsed.get("format", 1) or 1) == 2:
            prefix = self._v2_item_prefix()
            prefix_len = len(prefix)
            self._v2_rank_cache = sorted(
                rank
                for name in rows
                if name.startswith(prefix) and _v2_is_rank(rank := name[prefix_len:])
            )

    def to_list_from_rows(self, rows: dict[str, Any]) -> list[Any]:
        """Like to_list(), but served from a pre-fetched name->value mapping.

        v1: falls back to a per-item database read (via __getitem__) for
        any row missing from the mapping. Item decoding matches
        __getitem__: JSON with a raw-string fallback.

        v2: derived entirely from `rows` (no fallback reads -- there is no
        separate "recorded length" a v2 list could disagree with).

        Raises:
            ListCorruptionError: v1 only -- a row is missing from BOTH the
                mapping and storage.
        """
        if self._is_v2():
            prefix = self._v2_item_prefix()
            prefix_len = len(prefix)
            pairs = sorted(
                (rank, value)
                for name, value in rows.items()
                if name.startswith(prefix) and _v2_is_rank(rank := name[prefix_len:])
            )
            self._v2_rank_cache = [rank for rank, _ in pairs]
            return [self._decode_item(value) for _, value in pairs]

        length = len(self)
        result: list[Any] = []
        for i in range(length):
            item_str = rows.get(self._get_item_property_name(i))
            if item_str is None:
                # Not in the pre-fetched partition dump -- fall back to a
                # per-item read. __getitem__ raises ListCorruptionError if
                # the row is genuinely missing, not merely absent from
                # `rows`.
                result.append(self[i])
                continue
            try:
                result.append(json.loads(item_str))
            except (json.JSONDecodeError, TypeError):
                result.append(item_str)
        return result

    def get_description(self) -> str:
        """Get the description field for UI info about the list."""
        meta = self._load_metadata()
        description = meta.get("description", "")
        return str(description) if description is not None else ""

    def set_description(self, description: str) -> None:
        """Set the description field for UI info about the list."""
        meta = self._load_metadata()
        meta["description"] = description
        self._save_metadata(meta)

    def get_explanation(self) -> str:
        """Get the explanation field to be used for LLMs."""
        meta = self._load_metadata()
        explanation = meta.get("explanation", "")
        return str(explanation) if explanation is not None else ""

    def set_explanation(self, explanation: str) -> None:
        """Set the explanation field to be used for LLMs."""
        meta = self._load_metadata()
        meta["explanation"] = explanation
        self._save_metadata(meta)

    def get_metadata(self) -> dict[str, Any]:
        """
        Get list metadata as a read-only dictionary.

        Returns metadata including created_at, updated_at, version, item_type,
        chunk_size, and length. For description and explanation, use the
        dedicated get_description() and get_explanation() methods.

        Returns:
            Dictionary with metadata fields:
            - created_at: ISO timestamp when list was created
            - updated_at: ISO timestamp of last modification
            - version: Metadata schema version
            - item_type: Type of items stored (currently always "json")
            - chunk_size: Internal chunk size (currently always 1)
            - length: Number of items in the list

        Note: This returns a copy; modifications won't affect the stored metadata.
        Use set_description() and set_explanation() to update user-facing fields.
        """
        meta = self._load_metadata()
        # v2 has no stored length -- meta.get("length", 0) would silently
        # report 0 for every non-empty v2 list. len(self) counts it (and
        # is cheap after the first call, via the cached rank-key range).
        length = len(self) if self._is_v2() else meta.get("length", 0)
        return {
            "created_at": meta.get("created_at", ""),
            "updated_at": meta.get("updated_at", ""),
            "version": meta.get("version", ""),
            "item_type": meta.get("item_type", ""),
            "chunk_size": meta.get("chunk_size", 1),
            "length": length,
        }

    def __len__(self) -> int:
        """Get list length. v1: from metadata (no item loading). v2:
        counted from the (cached) rank-key range."""
        if self._is_v2():
            return len(self._v2_ensure_rank_cache())
        meta = self._load_metadata()
        length = meta.get("length", 0)
        return int(length) if length is not None else 0

    def _v2_getitem(self, index: int) -> Any:
        # Force a fresh rank read, for the same reason the positional writes
        # do: the cached rank at position i still EXISTS after another writer
        # inserts earlier in the list, so the missing-row fallback below never
        # fires and a stale read returns the item that used to be here. v1's
        # positional read is always current (it addresses the row by index
        # directly), and v2 should not be weaker.
        ranks = self._v2_ensure_rank_cache(force=True)
        length = len(ranks)
        orig_index = index
        if index < 0:
            index = length + index
        if index < 0 or index >= length:
            raise IndexError(f"List index {orig_index} out of range (length: {length})")

        rank = ranks[index]
        item_db = get_property(self.config)
        item_str = item_db.get(actor_id=self.actor_id, name=self._v2_item_name(rank))

        if item_str is None:
            # The cached rank list is stale (another instance mutated the
            # list between our cache load and this read) -- reload once
            # before concluding corruption. A concurrent mutation is a
            # normal race, not damaged storage.
            ranks = self._v2_ensure_rank_cache(force=True)
            if index < 0 or index >= len(ranks):
                raise IndexError(
                    f"List index {orig_index} out of range (length: {len(ranks)})"
                )
            rank = ranks[index]
            item_db = get_property(self.config)
            item_str = item_db.get(
                actor_id=self.actor_id, name=self._v2_item_name(rank)
            )
            if item_str is None:
                raise ListCorruptionError(self.name, index)

        return self._decode_item(item_str)

    def __getitem__(self, index: int) -> Any:
        """Get item by index, loading from database.

        Raises:
            IndexError: ``index`` is outside ``[0, len(self))``.
            ListCorruptionError: v1 only -- ``index`` is in range but the
                row is missing from storage. Under v2 this can only happen
                transiently under concurrent mutation, and is resolved by
                one cache reload (see ``_v2_getitem``) rather than raised.
        """
        if self._is_v2():
            return self._v2_getitem(index)

        length = len(self)

        if index < 0:
            index = length + index

        if index < 0 or index >= length:
            raise IndexError(f"List index {index} out of range (length: {length})")

        if not self._db:
            raise RuntimeError("No database connection available")

        item_property_name = self._get_item_property_name(index)
        # Use fresh DB instance to avoid handle conflicts
        item_db = get_property(self.config)
        item_str = item_db.get(actor_id=self.actor_id, name=item_property_name)

        if item_str is None:
            raise ListCorruptionError(self.name, index)

        try:
            return json.loads(item_str)
        except (json.JSONDecodeError, TypeError) as e:
            logger.error(f"Failed to parse list item at index {index}: {e}")
            return item_str  # Return raw string if JSON parsing fails

    def _v2_touch_metadata(self) -> None:
        """Persist the metadata row after a v2 item mutation.

        v2 doesn't store an authoritative length, so unlike v1 (where every
        mutation writes ``length`` into metadata as a side effect) nothing
        else forces the ``list:{name}-meta`` row to exist. But its
        existence IS load-bearing: ``PropertyListStore.exists()``,
        property/list name-collision detection, and ``list_all()`` all key
        off it. A list whose only mutations were append()/insert()/etc,
        with ``set_description()``/``set_explanation()`` never called,
        must still be discoverable -- so every v2 mutation persists
        metadata (matching v1's per-mutation write, just without a
        `length` field to update).
        """
        self._save_metadata(self._load_metadata())

    def _v2_setitem(self, index: int, value: Any) -> None:
        # Force a fresh rank read: this is a DESTRUCTIVE positional write,
        # and a cached rank list can be arbitrarily old on a long-lived
        # instance. If another writer inserted an item earlier in the list
        # since we cached, position i now names a different row than our
        # cache says -- and we would overwrite the wrong item. See
        # _v2_delitem for the same reasoning. (append()/insert() keep using
        # the cache: their conditional writes bound the damage to where an
        # item lands, never to destroying a different one.)
        ranks = self._v2_ensure_rank_cache(force=True)
        length = len(ranks)
        orig_index = index
        if index < 0:
            index = length + index
        if index < 0 or index >= length:
            raise IndexError(f"List index {orig_index} out of range (length: {length})")

        rank = ranks[index]
        value_str = self._encode_item(value)
        item_db = get_property(self.config)
        if not item_db.set(
            actor_id=self.actor_id, name=self._v2_item_name(rank), value=value_str
        ):
            raise RuntimeError(f"list item write failed for '{self.name}'[{index}]")
        self._v2_touch_metadata()

    def __setitem__(self, index: int, value: Any) -> None:
        """Set item at index."""
        self._maybe_lazy_migrate()
        if self._is_v2():
            self._v2_setitem(index, value)
            return

        length = len(self)

        if index < 0:
            index = length + index

        if index < 0 or index >= length:
            raise IndexError(f"List index {index} out of range (length: {length})")

        if not self._db:
            raise RuntimeError("No database connection available")

        # Serialize the value
        try:
            value_str = json.dumps(value)
        except (TypeError, ValueError):
            value_str = str(value)

        # Use fresh DB instance to avoid handle conflicts
        item_db = get_property(self.config)
        if not item_db.set(
            actor_id=self.actor_id,
            name=self._get_item_property_name(index),
            value=value_str,
        ):
            raise RuntimeError(f"list item write failed for '{self.name}'[{index}]")

        # Update metadata timestamp
        meta = self._load_metadata()
        self._save_metadata(meta)

    def _v2_delitem(self, index: int) -> None:
        # Force a fresh rank read before deleting by position -- a stale
        # cache would delete whichever item USED to be at this index. See
        # _v2_setitem.
        ranks = self._v2_ensure_rank_cache(force=True)
        length = len(ranks)
        orig_index = index
        if index < 0:
            index = length + index
        if index < 0 or index >= length:
            raise IndexError(f"List index {orig_index} out of range (length: {length})")

        rank = ranks[index]
        item_db = get_property(self.config)
        if not item_db.set(
            actor_id=self.actor_id, name=self._v2_item_name(rank), value=None
        ):
            raise RuntimeError(f"list item write failed for '{self.name}'[{index}]")

        # A single row delete IS the whole operation under v2 -- no shift
        # loop. Keep the cache consistent with the write we just made
        # (mutating the same list object _v2_ensure_rank_cache() returned).
        del ranks[index]
        self._v2_touch_metadata()

    def __delitem__(self, index: int) -> None:
        """Delete item at index and shift remaining items."""
        self._maybe_lazy_migrate()
        if self._is_v2():
            self._v2_delitem(index)
            return

        length = len(self)

        if index < 0:
            index = length + index

        if index < 0 or index >= length:
            raise IndexError(f"List index {index} out of range (length: {length})")

        if not self._db:
            raise RuntimeError("No database connection available")

        # Delete the item at index
        prop = get_property(self.config)
        if not prop.set(
            actor_id=self.actor_id,
            name=self._get_item_property_name(index),
            value=None,  # This will delete the property
        ):
            raise RuntimeError(f"list item write failed for '{self.name}'[{index}]")

        # Shift all items after index down by one
        for i in range(index + 1, length):
            # Use fresh DB instance to avoid handle conflicts
            item_db = get_property(self.config)
            item_value = item_db.get(
                actor_id=self.actor_id, name=self._get_item_property_name(i)
            )

            if item_value is not None:
                # Move item from position i to position i-1
                move_db = get_property(self.config)
                if not move_db.set(
                    actor_id=self.actor_id,
                    name=self._get_item_property_name(i - 1),
                    value=item_value,
                ):
                    raise RuntimeError(
                        f"list item write failed for '{self.name}'[{i - 1}]"
                    )

                # Delete the old position
                delete_db = get_property(self.config)
                if not delete_db.set(
                    actor_id=self.actor_id,
                    name=self._get_item_property_name(i),
                    value=None,
                ):
                    raise RuntimeError(f"list item write failed for '{self.name}'[{i}]")

        # Update metadata length
        meta = self._load_metadata()
        meta["length"] = length - 1
        self._save_metadata(meta)

    def __iter__(self) -> "ListPropertyIterator | Iterator[Any]":
        """Return an iterator over the list.

        v1: lazy, per-item loading (ListPropertyIterator). v2: one full
        range query up front (_v2_to_list()), then a plain list iterator --
        per-item __getitem__ calls in a loop would cost one query per item,
        which the range-read design exists specifically to avoid.
        """
        if self._is_v2():
            return iter(self._v2_to_list())
        return ListPropertyIterator(self)

    def _v2_append(self, item: Any) -> None:
        value_str = self._encode_item(item)
        for attempt in range(_V2_MAX_RANK_RETRIES):
            ranks = self._v2_ensure_rank_cache(force=(attempt > 0))
            last = ranks[-1] if ranks else None
            candidate = fi.generate_key_between(last, None)
            if len(candidate) > _V2_RANK_MAX_LEN:
                raise RuntimeError(
                    f"list '{self.name}' rank key exceeded {_V2_RANK_MAX_LEN} "
                    f"chars -- run compact() to rebalance"
                )
            item_db = get_property(self.config)
            if item_db.create_if_not_exists(
                actor_id=self.actor_id,
                name=self._v2_item_name(candidate),
                value=value_str,
            ):
                ranks.append(candidate)
                self._v2_touch_metadata()
                return
            # Collision: another writer took this rank between our cache
            # load and the write. Force-reread on the next attempt so the
            # regenerated key is based on the current actual last rank.
        raise RuntimeError(
            f"list '{self.name}' append: too many rank collisions, retry later"
        )

    def append(self, item: Any) -> None:
        """Add item to end of list."""
        if not self._db:
            raise RuntimeError("No database connection available")

        self._maybe_lazy_migrate()
        if self._is_v2():
            self._v2_append(item)
            return

        length = len(self)

        # Serialize the item
        try:
            item_str = json.dumps(item)
        except (TypeError, ValueError):
            item_str = str(item)

        # Store the new item - use fresh DB instance to avoid handle conflicts
        item_property_name = self._get_item_property_name(length)
        item_db = get_property(self.config)
        if not item_db.set(
            actor_id=self.actor_id, name=item_property_name, value=item_str
        ):
            raise RuntimeError(f"list item write failed for '{self.name}'[{length}]")
        logger.debug(
            f"append(): Stored item at '{item_property_name}' with value: {item_str}"
        )

        # Update metadata
        meta = self._load_metadata()
        meta["length"] = length + 1
        self._save_metadata(meta)

    def extend(self, items: list[Any]) -> None:
        """Add multiple items to end of list."""
        for item in items:
            self.append(item)

    def _v2_item_names_in_range(self) -> list[str]:
        """This list's OWN v2 item row names.

        Used by the destructive paths (``clear()``/``delete()``/migration
        cleanup), so the rank filter is load-bearing here, not merely
        cosmetic: a legacy ``#``-named sibling list's rows share this byte
        range and must never be deleted as if they were ours.
        """
        lower, upper = self._v2_bounds()
        db = get_property(self.config)
        rows = db.get_range(
            actor_id=self.actor_id, lower=lower, upper=upper, keys_only=True
        )
        prefix_len = len(self._v2_item_prefix())
        return [name for name in rows if _v2_is_rank(name[prefix_len:])]

    def clear(self) -> None:
        """Remove all items from list."""
        if not self._db:
            raise RuntimeError("No database connection available")

        if self._is_v2():
            for item_name in self._v2_item_names_in_range():
                item_db = get_property(self.config)
                if not item_db.set(actor_id=self.actor_id, name=item_name, value=None):
                    raise RuntimeError(
                        f"list item write failed for '{self.name}' during clear()"
                    )
            self._save_metadata(self._create_default_metadata_v2())
            self._v2_rank_cache = []
            return

        length = len(self)

        # Delete all item properties
        for i in range(length):
            item_db = get_property(self.config)
            if not item_db.set(
                actor_id=self.actor_id, name=self._get_item_property_name(i), value=None
            ):
                raise RuntimeError(f"list item write failed for '{self.name}'[{i}]")

        # Reset metadata
        meta = self._create_default_metadata()
        self._save_metadata(meta)

    def delete(self) -> None:
        """Delete the entire list including metadata."""
        if not self._db:
            raise RuntimeError("No database connection available")

        if self._is_v2():
            for item_name in self._v2_item_names_in_range():
                item_db = get_property(self.config)
                if not item_db.set(actor_id=self.actor_id, name=item_name, value=None):
                    raise RuntimeError(
                        f"list item write failed for '{self.name}' during delete()"
                    )
            meta_db = get_property(self.config)
            if not meta_db.set(
                actor_id=self.actor_id, name=self._get_meta_property_name(), value=None
            ):
                raise RuntimeError(f"list metadata write failed for '{self.name}'")
            self._meta_cache = None
            self._v2_rank_cache = None
            return

        length = len(self)

        # Delete all item properties
        for i in range(length):
            item_db = get_property(self.config)
            if not item_db.set(
                actor_id=self.actor_id, name=self._get_item_property_name(i), value=None
            ):
                raise RuntimeError(f"list item write failed for '{self.name}'[{i}]")

        # Delete metadata
        meta_db = get_property(self.config)
        if not meta_db.set(
            actor_id=self.actor_id, name=self._get_meta_property_name(), value=None
        ):
            raise RuntimeError(f"list metadata write failed for '{self.name}'")

        # Clear cache
        self._meta_cache = None

    def to_list(self) -> list[Any]:
        """Load entire list into memory.

        v2: exactly one range query, regardless of length.

        Raises:
            ListCorruptionError: v1 only -- a row within ``[0, len(self))``
                is missing from storage. Run ``compact()`` (or the caller's
                remedy) to repair, then retry. Not possible under v2 --
                there is no separate "recorded length" a v2 list's rows
                could disagree with.
        """
        if self._is_v2():
            return self._v2_to_list()

        length = len(self)
        result = []

        for i in range(length):
            result.append(self[i])

        return result

    def slice(self, start: int, end: int) -> list[Any]:
        """Load a range of items efficiently.

        v2: exactly one range query (the full list), sliced in memory --
        still one query, not one per requested item.

        Raises:
            ListCorruptionError: v1 only -- a row within the requested
                range is missing from storage.
        """
        if self._is_v2():
            values = self._v2_to_list()
            length = len(values)
            if start < 0:
                start = max(0, length + start)
            if end < 0:
                end = max(0, length + end)
            start = max(0, min(start, length))
            end = max(start, min(end, length))
            return values[start:end]

        length = len(self)

        # Handle negative indices
        if start < 0:
            start = max(0, length + start)
        if end < 0:
            end = max(0, length + end)

        # Clamp to valid range
        start = max(0, min(start, length))
        end = max(start, min(end, length))

        result = []
        for i in range(start, end):
            result.append(self[i])

        return result

    def to_indexed_list(self) -> list[tuple[int, Any]]:
        """Load the list as ``(index, item)`` pairs.

        This is the contract the ``/items`` REST accessor documents:
        ``index`` is whatever ``__getitem__``/``__setitem__``/
        ``__delitem__`` accept for this same list, so GET and
        update/delete actions always agree.

        v1: ``index`` IS the storage row's numeric suffix -- storage
        identity and position coincide.

        v2: storage identity is the row's rank key, NOT its position --
        ``index`` here is purely positional (``0..len-1``, derived from
        rank sort order), and every mutation method translates position ->
        rank internally. This is exactly the divergence this method's
        contract was written to keep correct.

        Raises:
            ListCorruptionError: v1 only -- see ``to_list()``.
        """
        return list(enumerate(self.to_list()))

    def _v2_pop(self, index: int) -> Any:
        """Read and remove the item at ``index``, resolving its rank ONCE.

        ``self[index]`` followed by ``del self[index]`` is not good enough
        under v2: each refreshes the rank map independently, so a concurrent
        mutation landing between them makes pop() return one item and delete
        a different one. Resolving the rank a single time and using it for
        both the read and the delete keeps the pair consistent — whatever it
        returns is exactly what it removed.
        """
        ranks = self._v2_ensure_rank_cache(force=True)
        length = len(ranks)
        orig_index = index
        if index < 0:
            index = length + index
        if index < 0 or index >= length:
            raise IndexError(f"List index {orig_index} out of range (length: {length})")

        rank = ranks[index]
        name = self._v2_item_name(rank)

        item_db = get_property(self.config)
        item_str = item_db.get(actor_id=self.actor_id, name=name)
        if item_str is None:
            raise ListCorruptionError(self.name, index)
        item = self._decode_item(item_str)

        del_db = get_property(self.config)
        if not del_db.set(actor_id=self.actor_id, name=name, value=None):
            raise RuntimeError(f"list item write failed for '{self.name}'[{index}]")

        del ranks[index]
        self._v2_touch_metadata()
        return item

    def pop(self, index: int = -1) -> Any:
        """Remove and return item at index (default last)."""
        if len(self) == 0:
            raise IndexError("pop from empty list")

        # Deliberately NOT calling _maybe_lazy_migrate() here: migration
        # closes holes in flight, so triggering it from pop() would make a
        # corrupted v1 list silently self-repair instead of raising, which
        # is the Phase 2/3 contract. The v1 branch below reaches
        # __delitem__, which triggers migration exactly as it always has.
        if self._is_v2():
            return self._v2_pop(index)

        if index == -1:
            index = len(self) - 1

        item = self[index]
        del self[index]
        return item

    def _v2_insert(self, index: int, item: Any) -> None:
        value_str = self._encode_item(item)
        for attempt in range(_V2_MAX_RANK_RETRIES):
            ranks = self._v2_ensure_rank_cache(force=(attempt > 0))
            length = len(ranks)
            pos = index
            if pos < 0:
                pos = max(0, length + pos)
            if pos > length:
                pos = length

            lower = ranks[pos - 1] if pos > 0 else None
            upper = ranks[pos] if pos < length else None
            candidate = fi.generate_key_between(lower, upper)
            if len(candidate) > _V2_RANK_MAX_LEN:
                raise RuntimeError(
                    f"list '{self.name}' rank key exceeded {_V2_RANK_MAX_LEN} "
                    f"chars -- run compact() to rebalance"
                )
            item_db = get_property(self.config)
            if item_db.create_if_not_exists(
                actor_id=self.actor_id,
                name=self._v2_item_name(candidate),
                value=value_str,
            ):
                ranks.insert(pos, candidate)
                self._v2_touch_metadata()
                return
            # Collision: force a fresh read (recomputing neighbours at this
            # position) on the next attempt.
        raise RuntimeError(
            f"list '{self.name}' insert: too many rank collisions, retry later"
        )

    def insert(self, index: int, item: Any) -> None:
        """Insert item at given index."""
        if not self._db:
            raise RuntimeError("No database connection available")

        self._maybe_lazy_migrate()
        if self._is_v2():
            self._v2_insert(index, item)
            return

        length = len(self)

        if index < 0:
            index = max(0, length + index)
        if index > length:
            index = length

        # Shift all items from index onwards up by one. Fresh DB instance
        # per call (like every other mutation method) — reusing self._db
        # across get()/set() calls for different item names left a stale
        # handle that, on DynamoDB, overwrote every shifted row with the
        # last-read value instead of its own.
        for i in range(length - 1, index - 1, -1):
            item_db = get_property(self.config)
            item_value = item_db.get(
                actor_id=self.actor_id, name=self._get_item_property_name(i)
            )

            if item_value is not None:
                move_db = get_property(self.config)
                if not move_db.set(
                    actor_id=self.actor_id,
                    name=self._get_item_property_name(i + 1),
                    value=item_value,
                ):
                    raise RuntimeError(
                        f"list item write failed for '{self.name}'[{i + 1}]"
                    )

        # Insert the new item
        try:
            item_str = json.dumps(item)
        except (TypeError, ValueError):
            item_str = str(item)

        insert_db = get_property(self.config)
        if not insert_db.set(
            actor_id=self.actor_id,
            name=self._get_item_property_name(index),
            value=item_str,
        ):
            raise RuntimeError(f"list item write failed for '{self.name}'[{index}]")

        # Update metadata
        meta = self._load_metadata()
        meta["length"] = length + 1
        self._save_metadata(meta)

    def _v2_remove(self, value: Any) -> None:
        """Delete the first item equal to ``value``, by RANK.

        Same hazard `_v2_pop` addresses, one method over: iterating to find
        the position and then deleting by that position resolves the rank map
        twice, so a concurrent mutation in between makes remove() delete
        whatever happens to sit at that position now rather than the item it
        matched. Deleting the rank the match came from removes exactly the
        item that was matched, or nothing.
        """
        pairs = self._v2_load_full()
        for i, (rank, raw_value) in enumerate(pairs):
            if self._decode_item(raw_value) != value:
                continue
            del_db = get_property(self.config)
            if not del_db.set(
                actor_id=self.actor_id, name=self._v2_item_name(rank), value=None
            ):
                raise RuntimeError(f"list item write failed for '{self.name}'[{i}]")
            # _v2_load_full() just set the cache to exactly these ranks in
            # this order, so dropping entry i keeps it consistent.
            ranks = self._v2_rank_cache
            if ranks is not None and i < len(ranks) and ranks[i] == rank:
                del ranks[i]
            else:  # pragma: no cover -- defensive
                self._v2_rank_cache = None
            self._v2_touch_metadata()
            return
        raise ValueError(f"{value} not in list")

    def remove(self, value: Any) -> None:
        """Remove first occurrence of value."""
        self._maybe_lazy_migrate()
        if self._is_v2():
            self._v2_remove(value)
            return

        for i, item in enumerate(self):
            if item == value:
                del self[i]
                return
        raise ValueError(f"{value} not in list")

    def index(self, value: Any, start: int = 0, stop: int | None = None) -> int:
        """Return index of first occurrence of value."""
        if self._is_v2():
            # One range query for the whole list, then scan in memory. Going
            # through self[i] would cost two queries PER ITEM now that
            # positional reads refresh the rank map, and it would compare
            # against a list that can shift under the loop.
            values = self._v2_to_list()
            if stop is None:
                stop = len(values)
            for i in range(max(0, start), min(stop, len(values))):
                if values[i] == value:
                    return i
            raise ValueError(f"{value} is not in list")

        length = len(self)
        if stop is None:
            stop = length

        for i in range(start, min(stop, length)):
            if self[i] == value:
                return i

        raise ValueError(f"{value} is not in list")

    def count(self, value: Any) -> int:
        """Return number of occurrences of value."""
        count = 0
        for item in self:
            if item == value:
                count += 1
        return count

    def _v2_verify(self) -> dict[str, Any]:
        """Read-only integrity check for v2 lists.

        Structurally, v2 cannot have holes or orphans -- there is no
        separate "recorded length" a row could disagree with; every
        present row IS a position. The only thing worth reporting is rank
        keys approaching the length cap (a signal to compact()/rebalance
        before insert()/append() start failing) and the same
        adjacent-duplicate heuristic v1 reports (informational, not part
        of ``healthy`` -- a duplicate value is never itself corruption
        under v2).

        Returns:
            Dict with:
            - format: 2
            - length: item count (one range query)
            - max_rank_length: the longest rank key currently in use
            - adjacent_duplicates: same heuristic as v1's verify(), but
              position-indexed pairs -- informational only
            - healthy: True iff no rank key is within the rebalance
              warning zone of the cap
        """
        pairs = self._v2_load_full()
        max_rank_length = max((len(rank) for rank, _ in pairs), default=0)

        adjacent_duplicates: list[tuple[int, int]] = []
        for i in range(len(pairs) - 1):
            if pairs[i][1] == pairs[i + 1][1]:
                adjacent_duplicates.append((i, i + 1))

        return {
            "format": 2,
            "length": len(pairs),
            "max_rank_length": max_rank_length,
            "adjacent_duplicates": adjacent_duplicates,
            "healthy": max_rank_length < _V2_RANK_MAX_LEN - 40,
        }

    def verify(self) -> dict[str, Any]:
        """Read-only integrity check against stored rows.

        v2: see ``_v2_verify()`` -- a structurally different report shape
        (no ``stored_length``/``missing_indices``/``orphan_indices``; those
        concepts don't exist when position IS the row's identity).

        v1 (below): fetches the actor's full property partition once and
        compares the metadata's ``length`` against which ``list:{name}-N``
        rows actually exist, in the range ``[0, length)``. Reports index
        numbers only -- never item values.

        Returns:
            Dict with:
            - stored_length: the metadata's recorded length
            - readable_count: how many of ``[0, stored_length)`` are present
            - missing_indices: indices in ``[0, stored_length)`` with no row
              (holes)
            - orphan_indices: rows present at or past ``stored_length``
            - adjacent_duplicates: list of ``(a, b)`` readable-index pairs
              where ``b == a + 1`` and both rows hold byte-identical stored
              content -- a heuristic; a legitimate list can hold two equal
              adjacent items, so this is a hint, not proof of corruption
            - healthy: True iff there are no holes, no orphans, and no
              adjacent-duplicate hits
        """
        if self._is_v2():
            return self._v2_verify()

        meta = self._load_metadata()
        stored_length = int(meta.get("length", 0) or 0)

        db_list = get_property_list(self.config)
        rows = db_list.fetch_all_including_lists(actor_id=self.actor_id) or {}

        pattern = re.compile(rf"^list:{re.escape(self.name)}-(\d+)$")
        present: set[int] = set()
        for key in rows:
            m = pattern.match(key)
            if m:
                present.add(int(m.group(1)))

        missing_indices = [i for i in range(stored_length) if i not in present]
        orphan_indices = sorted(i for i in present if i >= stored_length)
        readable_count = stored_length - len(missing_indices)

        ordered_present = [i for i in range(stored_length) if i in present]
        adjacent_duplicates: list[tuple[int, int]] = []
        for a, b in zip(ordered_present, ordered_present[1:], strict=False):
            if b != a + 1:
                continue
            va = rows.get(self._get_item_property_name(a))
            vb = rows.get(self._get_item_property_name(b))
            if va is not None and va == vb:
                adjacent_duplicates.append((a, b))

        return {
            "stored_length": stored_length,
            "readable_count": readable_count,
            "missing_indices": missing_indices,
            "orphan_indices": orphan_indices,
            "adjacent_duplicates": adjacent_duplicates,
            "healthy": not missing_indices
            and not orphan_indices
            and not adjacent_duplicates,
        }

    def _v2_compact(self) -> dict[str, Any]:
        """Rebalance a v2 list's rank keys back to short, evenly-spaced
        values.

        Regenerates ``n`` evenly distributed ranks with
        ``fractional_indexing.generate_n_keys_between(None, None, n)`` --
        deterministic for a given ``n``, so re-running compact() without
        the list changing in between converges to the same result. Rows
        whose target rank already matches their current rank are left
        untouched. For rows that need renaming, the write uses a plain
        ``set()`` only when the target name is unoccupied or is this same
        item's own current row; if the target collides with a DIFFERENT
        item's not-yet-renamed row, a nudged rank is generated between the
        last successfully written rank and the next target instead of
        overwriting it -- compact() never clobbers a row it hasn't gotten
        to yet. Old rows that didn't survive under their original name are
        deleted last, so a crash mid-compact leaves every item readable
        under either its old or new name, never neither.

        CRASH WINDOW (known limitation, deliberate trade): because new rows
        become visible before any old row is retired, a crash between the
        write loop and the cleanup loop leaves BOTH copies of every
        already-rewritten item in the authoritative range. Reads then return
        duplicates, and re-running compact() does not recover the original
        list -- it treats all 2n rows as genuine items and rebalances them.
        Recovery is manual: compare against a backup, or delete the stale
        copies (the old ranks are the ones NOT drawn from the evenly-spaced
        ``a0, a1, ...`` sequence a fresh rebalance produces).

        This is chosen over the alternative -- deleting each old row right
        after writing its replacement -- because that trades a visible
        failure for an invisible one. Targets are always ``a0, a1, ...``
        while old ranks may sort anywhere (a list built by repeated
        insert-at-0 has ranks below ``a0``), so retiring old rows
        incrementally makes intermediate states silently REORDERED rather
        than duplicated, and a reordered list passes every check
        ``verify()`` performs. Duplicate residue at least shows up in the
        data. A staged-commit protocol that is genuinely recoverable is
        tracked in ``thoughts/todo/v2-compact-staged-commit.md``.
        """
        report = self._v2_verify()

        if not self._db:
            raise RuntimeError("No database connection available")

        pairs = self._v2_load_full()
        n = len(pairs)
        old_ranks = [rank for rank, _ in pairs]
        old_names = {self._v2_item_name(rank) for rank in old_ranks}
        target_ranks = fi.generate_n_keys_between(None, None, n)

        written_ranks: list[str] = []
        for i, ((old_rank, value), target_rank) in enumerate(
            zip(pairs, target_ranks, strict=True)
        ):
            if target_rank == old_rank:
                written_ranks.append(old_rank)
                continue

            rank = target_rank
            for attempt in range(_V2_MAX_RANK_RETRIES + 1):
                new_name = self._v2_item_name(rank)
                if new_name not in old_names or rank == old_rank:
                    item_db = get_property(self.config)
                    if not item_db.set(
                        actor_id=self.actor_id, name=new_name, value=value
                    ):
                        raise RuntimeError(
                            f"list item write failed for '{self.name}' during compact()"
                        )
                    written_ranks.append(rank)
                    break
                if attempt == _V2_MAX_RANK_RETRIES:
                    raise RuntimeError(
                        f"compact() could not rebalance '{self.name}' -- "
                        f"rank collision storm"
                    )
                # Bisect between the rank that JUST collided and the next
                # unclaimed target boundary -- using the failed candidate
                # (not the last-written rank) as the new lower bound is
                # what makes each retry generate a genuinely different,
                # still-monotonic value instead of regenerating the same
                # collision forever.
                upper_idx = i + 1
                upper = target_ranks[upper_idx] if upper_idx < n else None
                rank = fi.generate_key_between(rank, upper)

        survivors = set(written_ranks)
        for old_rank in old_ranks:
            if old_rank not in survivors:
                del_db = get_property(self.config)
                if not del_db.set(
                    actor_id=self.actor_id,
                    name=self._v2_item_name(old_rank),
                    value=None,
                ):
                    raise RuntimeError(
                        f"list item write failed for '{self.name}' during compact() cleanup"
                    )

        self._v2_rank_cache = sorted(written_ranks)
        return report

    def compact(self) -> dict[str, Any]:
        """Repair holes and orphans by rewriting the list densely.

        v2: rebalances rank keys -- see ``_v2_compact()``.

        v1 (below): reads every row in ``[0, stored_length)`` that is
        actually present, in order, and rewrites them at ``0..n-1``;
        deletes every row from the new length through the highest index
        the list had (closing holes and removing orphans in one pass).
        ``description``, ``explanation`` and ``created_at`` are preserved
        -- unlike ``clear()`` + ``extend()``, which resets them via
        ``_create_default_metadata()``.

        Adjacent-duplicate residue (see ``verify()``) is left INTACT and
        reported, never rewritten: a duplicate always means a destroyed
        item, and silently collapsing one copy would bless the data loss
        as intentional rather than surface it.

        Returns:
            The ``verify()`` report this call acted on (taken before any
            write).
        """
        if self._is_v2():
            return self._v2_compact()

        report = self.verify()

        if not self._db:
            raise RuntimeError("No database connection available")

        stored_length = report["stored_length"]

        db_list = get_property_list(self.config)
        rows = db_list.fetch_all_including_lists(actor_id=self.actor_id) or {}

        ordered_values: list[str] = [
            rows[self._get_item_property_name(i)]
            for i in range(stored_length)
            if self._get_item_property_name(i) in rows
        ]

        for new_index, raw_value in enumerate(ordered_values):
            target_name = self._get_item_property_name(new_index)
            if rows.get(target_name) == raw_value:
                continue  # already correct -- skip the write
            item_db = get_property(self.config)
            if not item_db.set(
                actor_id=self.actor_id, name=target_name, value=raw_value
            ):
                raise RuntimeError(
                    f"list item write failed for '{self.name}'[{new_index}]"
                )

        highest_seen = max([stored_length - 1, *report["orphan_indices"]], default=-1)
        for i in range(len(ordered_values), highest_seen + 1):
            del_db = get_property(self.config)
            if not del_db.set(
                actor_id=self.actor_id, name=self._get_item_property_name(i), value=None
            ):
                raise RuntimeError(f"list item write failed for '{self.name}'[{i}]")

        meta = self._load_metadata()
        meta["length"] = len(ordered_values)
        self._save_metadata(meta)

        return report

    def migrate_to_v2(self) -> dict[str, Any]:
        """Migrate this list from v1 (dense integers) to v2 (fractional
        rank keys) storage, in place.

        Idempotent and safe to re-run after a crash at any point, and safe
        to re-run even if the v1 list was mutated between attempts:

        1. Refuse (log an operator-actionable error, list keeps serving
           v1) if the name contains ``#``, or if metadata is unparsable
           (``verify()`` -> ``_load_metadata()`` raises ``ValueError``,
           which propagates -- Phase 2's existing fail-fast behavior).
        2. ``verify()`` the v1 list. Holes are closed in-flight (only
           surviving rows migrate, in their existing order); duplicate
           residue migrates as both copies, as-is, and is reported.
        3. Clear any v2-range rows a PREVIOUS interrupted attempt left
           behind. This is what makes re-running safe even if the v1 list
           changed length in between: each attempt starts from a clean
           slate and regenerates a fresh, complete rank set from
           whatever the v1 list looks like right now, rather than trying
           to reconcile with a previous attempt's possibly-different rank
           count.
        4. Generate ``len(items)`` evenly distributed v2 ranks and write
           them (plain puts -- convergent on re-run because step 3 always
           clears first).
        5. Flip metadata to format 2 (drop ``length``) via a freshly read
           meta dict, so ``description``/``explanation``/``created_at``
           survive untouched.
        6. Delete the v1 item rows (idempotent -- a re-run just finds them
           already gone).

        A crash before step 5 leaves v1 fully authoritative: v1 reads and
        writes are completely unaffected (the half-written v2 rows are
        inert scratch space nothing reads), and the next attempt's step 3
        cleans them up before writing fresh ones. A crash after step 5
        leaves v2 authoritative with harmless leftover v1 rows -- v2
        readers already ignore v1-shaped rows, and step 6 is itself
        idempotent, so a re-run (or the bulk migration script) finishes
        the cleanup safely.

        Returns:
            Dict with ``migrated`` (bool) and either ``reason`` (str, only
            when not migrated) or ``item_count``/``had_holes``/
            ``duplicate_count`` (when migrated).
        """
        if _V2_RANK_MARKER in self.name:
            logger.error(
                f"List '{self.name}' cannot be migrated to v2: name "
                f"contains '{_V2_RANK_MARKER}', which is reserved for "
                f"internal storage keys -- rename the list before "
                f"migrating; it keeps working as v1 in the meantime"
            )
            return {"migrated": False, "reason": "name_contains_hash"}

        # Never decide "this list is v1" from a cached metadata dict. If
        # another instance (or process) migrated this list after we cached
        # its metadata, a stale read would send us down the v1 path: the v1
        # rows are gone, so verify() reports every index as a hole,
        # ordered_values comes back empty, and step 3 would delete the
        # now-authoritative v2 rows before writing an empty list over the
        # top -- silent, total data loss. Re-read from storage first.
        self._invalidate_cache()
        if self._is_v2():
            return {"migrated": False, "reason": "already_v2"}

        report = self.verify()

        if not self._db:
            raise RuntimeError("No database connection available")

        stored_length = report["stored_length"]

        db_list = get_property_list(self.config)
        rows = db_list.fetch_all_including_lists(actor_id=self.actor_id) or {}

        ordered_values: list[str] = [
            rows[self._get_item_property_name(i)]
            for i in range(stored_length)
            if self._get_item_property_name(i) in rows
        ]

        # Re-check the stored format one last time before the first
        # destructive write. The gap between the check above and here spans
        # verify()'s and fetch_all_including_lists()' partition reads -- wide
        # enough for a concurrent migration to land in it. Reading the meta
        # row directly (not through the cache, which verify() just
        # repopulated) is what makes this a real second look.
        format_db = get_property(self.config)
        current_meta_str = format_db.get(
            actor_id=self.actor_id, name=self._get_meta_property_name()
        )
        if current_meta_str:
            try:
                current_meta = json.loads(current_meta_str)
            except (json.JSONDecodeError, TypeError):
                current_meta = None
            if isinstance(current_meta, dict) and current_meta.get("format") == 2:
                logger.info(
                    f"List '{self.name}' was migrated to v2 concurrently -- "
                    f"abandoning this attempt without touching its rows"
                )
                self._invalidate_cache()
                return {"migrated": False, "reason": "already_v2"}

        # Step 3: clear any v2 scratch rows a previous interrupted attempt
        # left -- guarantees convergence regardless of what happened (or
        # changed) between attempts.
        for leftover_name in self._v2_item_names_in_range():
            del_db = get_property(self.config)
            if not del_db.set(actor_id=self.actor_id, name=leftover_name, value=None):
                raise RuntimeError(
                    f"list item write failed for '{self.name}' during "
                    f"migrate_to_v2() cleanup"
                )

        # Step 4: write the fresh v2 rows.
        ranks = fi.generate_n_keys_between(None, None, len(ordered_values))
        for rank, raw_value in zip(ranks, ordered_values, strict=True):
            item_db = get_property(self.config)
            if not item_db.set(
                actor_id=self.actor_id,
                name=self._v2_item_name(rank),
                value=raw_value,
            ):
                raise RuntimeError(
                    f"list item write failed for '{self.name}' during migrate_to_v2()"
                )

        # Step 5: flip metadata (fresh read -- preserves description/
        # explanation/created_at untouched).
        meta_db = get_property(self.config)
        meta_str = meta_db.get(
            actor_id=self.actor_id, name=self._get_meta_property_name()
        )
        meta = json.loads(meta_str) if meta_str else self._create_default_metadata_v2()
        meta.pop("length", None)
        meta["format"] = 2
        self._save_metadata(meta)
        self._v2_rank_cache = list(ranks)

        # Step 6: delete the v1 item rows (holes + orphans included).
        highest_seen = max([stored_length - 1, *report["orphan_indices"]], default=-1)
        for i in range(highest_seen + 1):
            del_db = get_property(self.config)
            if not del_db.set(
                actor_id=self.actor_id, name=self._get_item_property_name(i), value=None
            ):
                raise RuntimeError(
                    f"list item write failed for '{self.name}' during "
                    f"migrate_to_v2() v1 cleanup"
                )

        return {
            "migrated": True,
            "item_count": len(ordered_values),
            "had_holes": bool(report["missing_indices"]),
            "duplicate_count": len(report["adjacent_duplicates"]),
        }

    def _maybe_lazy_migrate(self) -> None:
        """Opportunistically migrate a small v1 list to v2 at the top of a
        mutation method.

        Best-effort: a failure here is logged and swallowed -- the
        original v1 mutation proceeds unaffected, because migration is a
        background upgrade, not a functional requirement for
        append()/insert()/etc to succeed. Only ever called from mutation
        methods, never from read paths (reads run under read-only
        permission -- handlers/properties.py, www.py).

        Larger v1 lists (``length > 50``) are left alone; they stay fully
        functional via the hardened v1 paths until
        ``scripts/migrate_property_lists.py`` runs.
        """
        if self._is_v2():
            return
        meta = self._load_metadata()
        length = int(meta.get("length", 0) or 0)
        if length > _V2_LAZY_MIGRATION_MAX_LENGTH:
            return
        try:
            self.migrate_to_v2()
        except Exception as e:
            logger.warning(
                f"Lazy migration to v2 failed for list '{self.name}': {e} "
                f"-- continuing as v1"
            )
